trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  group: TestingBotSecrets

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Optional: If using TestingBot CLI tasks
- task: TBMain@0
  inputs:
    connectedServiceName: 'testingbot service'

# Check TestingBot Connectivity
- script: |
    curl -I https://hub.testingbot.com/wd/hub/status
  displayName: "Check TestingBot Connectivity"

# Show environment variables
- script: |
    echo "TB_KEY is: $TB_KEY"
    echo "TB_SECRET is: $TB_SECRET"
    env | grep TB_
  displayName: "Check Variable Values"

# Install Appium & Appium Doctor
- script: |
    npm install -g appium
    npm install -g appium-doctor
  displayName: 'Install Appium & Appium Doctor'

# Run Appium Doctor
- script: |
    appium-doctor
  displayName: 'Run Appium Doctor'

# Install NPM packages
- script: |
    npm ci
  displayName: 'Install NPM Packages'

# Run WebDriverIO Tests
- script: |
    export TB_KEY=${TB_KEY}
    export TB_SECRET=${TB_SECRET}
    npx wdio run wdio.testingbot.conf.js
  displayName: 'Run WebDriverIO Tests'
