trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  TB_KEY: 'c8a2fdeacfb79fd59689a40a3a84f0dc'
  TB_SECRET: '4a78da7741abf8784b9b64d370f3c204'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Optional: If using TestingBot CLI tasks
- task: TBMain@0
  inputs:
    connectedServiceName: 'testingbot service'

- script: |
    npm install -g appium
    npm install -g appium-doctor
  displayName: 'Install Appium & Appium doctor'

# Optional: Appium Doctor (auto-confirmed)
- script: appium-doctor
  displayName: 'Run Appium Doctor'

# Install dependencies (optional but highly recommended)
- script: |
    npm ci
  displayName: 'Install NPM packages'

# Run WebDriverIO Tests
- script: |
    export TB_KEY=$TB_KEY
    export TB_SECRET=$TB_SECRET
    npx wdio run wdio.testingbot.conf.js
  displayName: 'Running Tests'
