trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# Optional: If using TestingBot CLI tasks
- task: TBMain@0
  inputs:
    connectedServiceName: 'testingbot service'

- script: |
    npm install -g appium
    npm install -g appium-doctor
  displayName: 'Install Appium & Appium doctor'

# Optional: Appium Doctor (auto-confirmed)
- script: appium-doctor
  displayName: 'Run Appium Doctor'

# Install dependencies (optional but highly recommended)
- script: |
    npm ci
  displayName: 'Install NPM packages'

# Run WebDriverIO Tests
- script: |
    export TB_KEY=$TB_KEY
    export TB_SECRET=$TB_SECRET
    npx wdio run wdio.testingbot.conf.js
  displayName: 'Running Tests'
