# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      curl -I https://hub.testingbot.com/wd/hub/status
    displayName: "Check TestingBot Connectivity"

  - script: |
      echo "TB_KEY is: $TB_KEY"
      echo "TB_SECRET is: $TB_SECRET"
      env | grep TB_
    env:
      TB_KEY: $(TESTINGBOT_KEY)
      TB_SECRET: $(TESTINGBOT_SECRET)
    displayName: "Check Variables Value"

  - script: |
      export TB_KEY=$TB_KEY
      export TB_SECRET=$TB_SECRET
      npx wdio run wdio.testingbot.conf.js
    env:
      TB_KEY: $(TESTINGBOT_KEY)
      TB_SECRET: $(TESTINGBOT_SECRET)
    displayName: 'Run Appium Tests on TestingBot'

